### ISSUE TITLE
Scraping Liquipedia pages

### ISSUE THREAD

**Issue by FO-nTTaX** [fireattack/ti_player_age#1]
Hello, I see you've written a scraper for Liquipedia. It would be much appreciated if you could use our API instead, which you can find at https://liquipedia.net/dota2/api.php

You can find relevant documentation either here: https://www.mediawiki.org/wiki/API:Revisions or here: https://www.mediawiki.org/wiki/API:Parsing_wikitext

Please also adhere to our API guidelines as outlined here: https://liquipedia.net/commons/Liquipedia:API_Usage_Guidelines

Thank you very much

**Comment by fireattack** [comment]
I don't think that's possible to use API to get HTML webpage.

**Comment by FO-nTTaX** [comment]
It is possible, I literally linked you the manual on how to do it. The parsing wikitext API gives you exactly what you need.

**Comment by fireattack** [comment]
I didn't use "wikitext" though, I use the generated HTML content. I've tried lots actions from the manual, and none of them return that. 

See also: https://stackoverflow.com/questions/1625162/get-text-content-from-mediawiki-page-via-api

**Comment by fireattack** [comment]
Never mind, I just found it's the parameter `rvparse`.

**Comment by FO-nTTaX** [comment]
The API can also give back parsed html for a title of a page. There's a good amount of ways getting it via API, and I'd appreciate if you wouldn't scrape our full pages without using the API. Thank you very much.

**Comment by fireattack** [comment]
I totally get your concern, but I already get what I need and am not going to run this script anymore. 

Debugging around how to use it the API way will only practically create more requests to your server.

**Comment by fireattack** [comment]
Rewrote using API, wish I did it correctly.
